name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/spring-data-multi-datasource
  pull_request:
    branches:
      - main
      - feature/spring-data-multi-datasource

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Checkstyle
        run: mvn checkstyle:check

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'


      - name: Run tests with Maven
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build the package
        run: mvn package

      - name: Set up GitHub authentication
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish package to GitHub Packages
        run: mvn deploy
